import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
	const { data: session, status } = useSession();
	const router = useRouter();

	console.log('🚀 ~ file: index.tsx ~ line 9 ~ session, status', session, status);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{session ? (
				<button onClick={() => signOut()}>Sign out</button>
			) : (
				<button onClick={() => router.push('/api/auth/signin')}>Sign in</button>
			)}
		</div>
	);
};

export default Home;
